### ISSUE TITLE
Rearrange figure captions in output XML

### ISSUE THREAD

**Issue by axfelix** [pkp/ots#107]
We need to make one more sanitization to technically-correct JATS to make Texture happy, per https://github.com/substance/texture/issues/252.

https://github.com/pkp/ots/commit/6e88b23056ee7a4eb97e5974cef065435cb23883 *should* do it (and I can reproduce it working on minimal examples) but it doesn't seem to be working properly in our stack. Would appreciate if someone who has more experience with php DOM stuff could take a look.

**Comment by kaschioudi** [comment]
@axfelix : https://github.com/pkp/ots/pull/108

**Comment by axfelix** [comment]
Working! thanks
