### ISSUE TITLE
Error with unittest.sh

### ISSUE THREAD

**Issue by etouceda** [pkp/ots#118]
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /var/www/html/phpunit.xml

..............................E

Time: 3.14 seconds, Memory: 64.50MB

There was 1 error:

1) BibtexreferencesConversionTest\Model\Queue\BibtexreferencesJobTest::testConversion
Exception: Couldn't find the stage document

/var/www/html/module/BibtexreferencesConversion/src/BibtexreferencesConversion/Model/Queue/Job/BibtexreferencesJob.php:29
/var/www/html/module/BibtexreferencesConversion/test/BibtexreferencesConversionTest/Model/Queue/BibtexreferencesJobTest.php:47

FAILURES!
Tests: 31, Assertions: 95, Errors: 1.

**Comment by etouceda** [comment]
Good Morning
I just made a clean installation and I get the above error, so I read in the forum should be solved.
The web works perfectly, but when processing any document it is put in Failed state.
You can not see anything in the error log.

a greeting

**Comment by etouceda** [comment]
Hi

I've been doing tests with a normal user and as an administrator watching the errors that appear. The error is as follows:

2018/02/28 16:32:33 |   | ERR | A worker threw an exception in GrobidConversion\Model\Queue\Job\GrobidJob:Unable to start Grobid service

But the service is:
43883  0.1  0.5 350428 43032 pts/1    S    16:30   0:00 php public/index.php queue doctrine grobid --start

Thanks

**Comment by axfelix** [comment]
Hi,

Might want to try installing for this first: https://github.com/axfelix/ots-vagrant

There's lots of messy steps in getting OTS up and running otherwise...

**Comment by etouceda** [comment]
Hi
Thanks I will try this.

**Comment by etouceda** [comment]
Good Morning
Since the machine with vagrant works correctly. It would be feasible to perform an installation using the steps of xmlps.sh or change the ip of the virtual machine to test in the local network.

Thanks

**Comment by axfelix** [comment]
No problem, glad that helped!
