### ISSUE TITLE
Affiliation in wrong position in the XML.

### ISSUE THREAD

**Issue by fabiobatalha** [pkp/ots#120]
Affiliation should be after contrib-group

![screenshot from 2018-02-28 13-55-19](https://user-images.githubusercontent.com/504142/36806783-2358fd3c-1c8f-11e8-9229-d61697f56ba5.png)

Erros happens in job: 2645

**Comment by axfelix** [comment]
Looks like this happens when no pub-date is found, due to some roundabout logic ... let me see what I can do here.

**Comment by axfelix** [comment]
Should be fixed in https://github.com/pkp/ots/commit/987bcaf269bb5717facf246df2318da18b2f47a3
