### ISSUE TITLE
Data loss after saving document in Texture

### ISSUE THREAD

**Issue by fabiobatalha** [pkp/ots#126]
OTS is retrieving XML files where the element **institution** do not have the attribute **content-type**.
 
The **institution** element in this condition is not being recognized by Texture, the content inside this element is lost after saving a document in texture.

It is probably happening because of the absence of the attribute **content-type** with one of the values: orgname, orgdiv1 or orgdiv2.

![screenshot from 2018-03-02 10-29-48](https://user-images.githubusercontent.com/504142/36906761-c79327da-1e04-11e8-8e30-aaee51075132.png)

**Comment by fabiobatalha** [comment]
Please do not consider the quality of the metadata inside the element institution.

**Comment by axfelix** [comment]
@michael, can you confirm this is likely what's happening?

**Comment by michael** [comment]
@axfelix yes I can confirm. See this specification here: 

https://github.com/substance/dar/blob/master/DarArticle.md#aff

If you don't have structured data for the affiliation, you could do some guessing to split up into individual fields or just put the whole string into orgname (then users can structure manually in Texture).

**Comment by axfelix** [comment]
OK, thanks, will make that change.
