### ISSUE TITLE
xref in the body do not match any reference id in the back.

### ISSUE THREAD

**Issue by fabiobatalha** [pkp/ots#130]
Example of xref in the body:

``` xml
<xref ref-type="bibr" id="IDa1dea654-f33b-4e78-a33b-93b72f12de04">
```

The ID's in the body is a sort of UUID value while the references id are a sequential value like R1, R2, R3.....

This behaviour leads to invalid xref matching in Texture.

![screenshot from 2018-03-02 15-54-09](https://user-images.githubusercontent.com/504142/36921439-61bb643a-1e32-11e8-9c1c-5486d81ad71a.png)

**Comment by fabiobatalha** [comment]
Not only Texture. Any other tools will not be able to use it, all of these xref ids must be fixed manually.

**Comment by axfelix** [comment]
As in https://github.com/pkp/ots/issues/128, this usually just means we failed to match citations to the reference list -- there would be an `rid` attribute of xref if they were matched.

**Comment by fabiobatalha** [comment]
Oh sorry, I thought I didn't open this issue.... You were fast in close the other one.
