### ISSUE TITLE
Default to APA Citation style if none is provided

### ISSUE THREAD

**Issue by axfelix** [pkp/ots#132]
For simplicity's sake, especially when using batch conversion with the OJS plugin, we should allow users to post to our API without specifying a citation style, and automatically select a default for them rather than throwing an error.

My choice is to use APA for this, which is currently tied to the hash 3f0f7fede090f24cc71b7281073996be -- however, I'm not sure if the hashes will change when the CSL registry updates, so we *might* need to alias APA to an arbitrary value (like `1`) if we're going to hardcode this behaviour.

**Comment by kaschioudi** [comment]
@axfelix : here's the PR https://github.com/pkp/ots/pull/133
