### ISSUE TITLE
Bump Texture version

### ISSUE THREAD

**Issue by axfelix** [pkp/ots#146]
Texture just did a new RC, so we should bump the version we're using.

@kaschioudi, we should document how we're doing this -- right now as far as I can tell, I can can get all of the files needed for a drop-in replacement (since there are no more API changes expected) by cloning the Texture repo, doing an `npm install`, and then looking in the `dist` directory that's created for all of the files that we currently ship in `https://github.com/pkp/ots/tree/master/public/texture`. It looks like we have our own `app.js` to hack in a save button, which is good, but I didn't realize we also have to make changes to the upstream `editor.js` to get that save button to work (and I'm assuming that's an untouched upstream `jquery.min.js` in the same directory).

So, is it the case right now that when there's a new Texture release, we have to replace the relevant files, *and* make edits to `editor.js`?

**Comment by kaschioudi** [comment]
@axfelix : you steps are correct. As long as texture's API do not change, all you need to do is replace texture's and substance's CSS and Javascript files. 

> but I didn't realize we also have to make changes to the upstream editor.js to get that save button to work

actually this is where the integration happens. I could have named the file anything. I am just reusing `editor.js` because that's the name used for their examples.

**Comment by axfelix** [comment]
Ohhhh, so `editor.js` is actually our file, like `app.js`, and the only js I should be replacing is `substance.js` and `texture.js`?

**Comment by kaschioudi** [comment]
that's correct.

**Comment by axfelix** [comment]
Thanks! done in https://github.com/pkp/ots/commit/5085a56a07aa9abcad31d9f7f56b66737ce3be5a
