### ISSUE TITLE
Update included version of Texture

### ISSUE THREAD

**Issue by axfelix** [pkp/ots#96]
After we figure out what needs to happen for Alpha 3 to work inside OJS (https://github.com/kaschioudi/ojs3-markup/issues/27) we should also update Texture in OTS.

**Comment by kaschioudi** [comment]
@axfelix : see https://github.com/pkp/ots/commit/43f818de881c44698ca156b24ec9c05a813f1337

However saving from texture seems to be broken. Either I'm doing something wrong or there's a bug in texture. This affects https://github.com/kaschioudi/ojs3-markup/issues/27 as well.

**Comment by axfelix** [comment]
Thanks, working! I still need to clean up our metadata output to make their validator a little happier though...

**Comment by axfelix** [comment]
Leaving open pending save bugs, though...
